### ISSUE TITLE
Feature Request:  Attach instance store on g2.2xlarge instances

### ISSUE THREAD

**Issue by putty182** [williamparry/cloudRIG#106]
g2.xlarge supports 1x 60GB SSD instance store at no extra cost;  while it obviously won't fit most AAA titles and all data written to it will disappear once instances shutdown/terminate, for the casual cloud gamer it's pretty useful.

The following seems to work - I'll try pack this into a PR if I get a chance.

1.  Add instance store to [ec2.runInstances()](https://github.com/williamparry/cloudRIG/blob/master/lib/index.js#L2651) 
````
ec2.runInstances(
    {
        BlockDeviceMappings: [{
            "DeviceName": "/dev/xvdca",
            "VirtualName": "ephemeral0"
        }],
        ...
````

2. Run `InitizlizeDisks.ps1` on each launch, or `InitizlizeDisks.ps1 -Schedule` ([doco](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2launch.html#ec2launch-mapping))  while [creating a new rig](https://github.com/williamparry/cloudRIG/blob/master/lib/index.js#L2848) from the base image

**Comment by williamparry** [comment]
That's great! Does it appear as a separate drive, and detach/delete when you shut down?

Part of the reason the default instance storage is so low is so that the snapshot speed is quick for saving the state.

**Comment by williamparry** [comment]
Merged into dev

**Comment by putty182** [comment]
[Instance storage](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html) != [Root device storage](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/RootDeviceStorage.html)  

I agree, keeping the boot/root volume small for quick snapshots and lower costs are both good things!

From a users perspective the instance storage volume is more comparable to a "ramdisk" but backed by SSD hardware.  While it's possible to attach multiple 50GB instance stores for extra storage, only one is provided free-of-charge with g2.2xlarge instances.

I've not tried customising what drive letter it appears as;  while the EC2-Launch doco mentions it's possible, `InitializeDisks.ps1` seems to always assign it `Z:\` after formatting which is good enough for me.  It also creates a text file in the root of the drive explaining that any data stored on it will be lost whenever the instance stops/terminates.  If this script doesn't run or fails, the instance store still appears in Disk Management but will need to be formatted and assigned a drive letter manually.

No need to detach/delete;  AWS won't snapshot instance stores, and specifying them at launch seems to be more reliable than specifying them in an AMI (plus I didn't want to mess with the Lambda scripts :p)

I'm currently using this setup to:
1.  Start cloudRIG using the cli app
2.  Turn on the kettle
3.  Defy [Blizzard's EULA](https://blog.parsecgaming.com/blizzards-cloud-gaming-mistake-30c615b4c126) and install D3 to `Z:\`
4.  Make a tea
5.  Play D3

10~20 minutes from start to gaming (when things go well).

**Comment by williamparry** [comment]
Thanks for explaining, and the new feature :) I've merged it into dev.

It's really cool to hear how people use cloudRIG. 10 - 20mins seems like a long time, but I'm not sure how much more can be done to speed it up. Any ideas?
