### ISSUE TITLE
Linux compatibility & advantages over Parsec's servers

### ISSUE THREAD

**Issue by gunar** [williamparry/cloudRIG#114]
Would it be possible to run cloudRIG on linux? Seeing that it's a Nodejs app, there should be not problem.

**Comment by williamparry** [comment]
Hi, the CLI should work for Linux. If you want to try and get the GUI working [there's $30 in it](https://github.com/williamparry/cloudRIG/issues/73) :)

**Comment by gunar** [comment]
*Offtopic*
Is there any advantage to using cloudRIG over hiring a machine from parsec? They say they don't charge any fees and comparing to AWS Prices it really seems so.

**Comment by Autotonic** [comment]
>Would it be possible to run cloudRIG on linux? Seeing that it's a Nodejs app, there should be not problem.

Absolutely, cloudRIG (CLI and GUI) works as expected under Ubuntu 18.04 LTS. Once you build you'll get an appimage, it only complains about this repo missing a `latest-linux.yml`

> Is there any advantage to using cloudRIG over hiring a machine from parsec? They say they don't charge any fees and comparing to AWS Prices it really seems so.

For me cloudRIG has 3 advantages:

1. cloudRIG uses AWS' spot instances (which is where the $0.13/hr figure comes from). At the time of writing a g2.2xlarge (North Virginia) is $0.442/hr compared to Parsec's $0.77/hr

2. Settings your own EBS volume size. Parsec's smallest storage option is 100GB for $10 a month, which is inline with AWS EBS pricing. cloudRIG can use your own EBS volume size if you only needed say 20GB for $2 a month

3. It's more of a "pay as you go" versus Parsec's paying for a set amount of time.

If you do go with Parsec's server rental, be sure to double check the server's location.
