### ISSUE TITLE
Cannot read property 'ImageId' of undefined [CLI/Linux]

### ISSUE THREAD

**Issue by gunar** [williamparry/cloudRIG#116]
I believe this is because the Parsec image doesn't exist in sa-east-1 yet. Is there anyway I can copy it over from another region?

**Comment by gunar** [comment]
Probably because `sa-east-1a` does not have GPU optimized machines at this moment.

**Comment by ywaf** [comment]
Hey Guys, I am starting to have this issue on the macOS Gui version. It was working about 2 months ago but it stopped working now. Region: ap-southeast-2 (Sydney). Any solutions?

**Comment by NitriKx** [comment]
The parsec image is only used on the first run. Cloudrig then create a new one on each shutdown.
In which context do you have this error ? 
Note: this repo is now deprecated and you should post your issues on cloudrig/cloudrig

**Comment by ywaf** [comment]
Hey, whenever I press start it comes up with the error about 5 sec later. It was definitely working about a month ago. Thanks
