### ISSUE TITLE
Migrating a cloudrig snapshot to a new availability zone?

### ISSUE THREAD

**Issue by pjz** [williamparry/cloudRIG#128]
I'd like to migrate my cloudrig from one availability zone to another.  How can I do so?  I'm comfortable with the aws web console, and also have the aws cli installed on my Linux machine.  I've copied the Snapshot [edit: and AMI!] over to the target availability zone, but... how do i get it to be 'discovered' by cloudRIG?  It seems to want to make a new image for me.  Or would it be easier to just let it make a new image for me and then rename my copied-over image to that one somehow?  Please help!

**Comment by NitriKx** [comment]
Hi @pjz, an AMI can be launch on all the AZ of the AWS Region. 
What I'm doing to change the AZ is that I came back to the first menu (configure), change the AZ and then continue the wizard with it. Then cloudRIG will automatically use the AMI already created. 
Is that solving your problem?

**Comment by pjz** [comment]
I had to re-tag the AMI once I copied it over, was the problem. For the record, to shift to a new region, you need to:
  1. Find your Snapshot, copy it to the new region.
  2. Find your AMI, copy it to the new region.
  3. Fix the tags on the AMI. ('cloudrig' = 'true', I believe)
  4. Point cloudrig at the new region.
