### ISSUE TITLE
waitFor's returning early

### ISSUE THREAD

**Issue by williamparry** [williamparry/cloudRIG#31]
instanceTerminated and instanceOk are returning early, so I'm relying on timeouts, which sucks.

**Comment by akshitgrover** [comment]
@williamparry When is it returning, I mean which route?

**Comment by williamparry** [comment]
During the shut down: https://github.com/williamparry/cloudRIG/blob/master/lib/services/instance.js#L1321

And I think during reboot there were issues:
https://github.com/williamparry/cloudRIG/blob/master/lib/services/instance.js#L1415
https://github.com/williamparry/cloudRIG/blob/master/lib/services/instance.js#L1392

**Comment by akshitgrover** [comment]
Ok, I will see if I can help. @williamparry

**Comment by williamparry** [comment]
One way to get around it is to remove waitFor's and poll the state.

**Comment by williamparry** [comment]
Haven't seen this recently. Closing.
