### ISSUE TITLE
Auto extend from toast notification [$50]

### ISSUE THREAD

**Issue by williamparry** [williamparry/cloudRIG#46]
Give the option to cancel the scheduled shutdown: https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/adaptive-interactive-toasts

**Comment by williamparry** [comment]
Notification should also appear over the game.

**Comment by williamparry** [comment]
https://www.bountysource.com/issues/51584123-auto-extend-from-toast-notification

**Comment by artem7902** [comment]
I have a problem with creating Powershell script, it works good for simple notification, but I don't know how to bind button click to cancel instance. Will It be ok if I create some c# app for creating a notification and handle click?

**Comment by williamparry** [comment]
Sure, I'd like to use the same application for [this issue also](https://github.com/williamparry/cloudRIG/issues/76) (which I'll look at), so there'll need to be a flag that can be set to enable "cancel instance" or not (if it's AWS mandated, then they can't extend).

Could you write it in dotnet core and add it as a folder in lib?

I'd look at using the C# AWS SDK to be able to remove the cloudwatch scheduled event.

**Comment by artem7902** [comment]
Got it.

> Could you write it in dotnet core and add it as a folder in lib?
Yes, just need time for reading the documentation, I have small experience with c#.

**Comment by williamparry** [comment]
Bounty increased to $50 :)

**Comment by artem7902** [comment]
Thanks, I think it's worth it. I create pull request, but for correct work, you need:
1. Build project with release configuration and put the content of bin/Release folder to "C:\ProgramData\Amazon\EC2-Windows\Launch\Apps\CancelShutdownApp\" and put toast.xml file to "C:\ProgramData\Amazon\EC2-Windows\Launch\Apps\CancelShutdownApp\xml"  
![image](https://user-images.githubusercontent.com/26010756/37565220-aceeb402-2aad-11e8-98b5-ca3cf4a9897e.png)
2. Manually change visual time for toast notification to 1 minute, I tried to change it using SSM but it doesn't work.
![image](https://user-images.githubusercontent.com/26010756/37565234-067f7b5a-2aae-11e8-8a40-3b00022d6dae.png)
As I understand you can modify primary AMI for add these changes. #78
