### ISSUE TITLE
Extend EBS

### ISSUE THREAD

**Issue by williamparry** [williamparry/cloudRIG#48]
Ability to extend an EBS volume (and have it update in the instance)

**Comment by williamparry** [comment]
https://www.bountysource.com/issues/51622442-extend-ebs

**Comment by williamparry** [comment]
I get the sense this will need to be coupled with some Powershell. There's a sendMessage function in the lib where you can pass in Powershell. I'd be OK with the performance hit to get this across the line with a Powershell command attached to the end of the start sequence that always runs to check that the volume has expanded.

**Comment by artem7902** [comment]
#69

**Comment by williamparry** [comment]
Reckon you can claim this bounty :)
