### ISSUE TITLE
Second volume not being attached

### ISSUE THREAD

**Issue by yunyu** [williamparry/cloudRIG#55]
After I shut down an instance and started it up, the second 150GB volume I'm using is not automatically attached. Attaching it causes the instance to shut down.

**Comment by yunyu** [comment]
I think the main problem is that the library is hanging on _waitForInstanceOk, even when the instance is launched. A subsequent get state works.

**Comment by williamparry** [comment]
_waitForInstanceOK can take a long time, and yeah if it hangs it won't get to:

https://github.com/williamparry/cloudRIG/blob/master/lib/index.js#L2168

Can you post your replication steps such as if you're using a saved previous cloudRIG AMI and whether it's a new volume or an existing one?

**Comment by yunyu** [comment]
Yeah, that makes sense. Would it be feasible to continually do the equivalent of "get status" instead, as that seems to be faster?

I'm using a previous AMI, and it is an existing volume.

**Comment by yunyu** [comment]
This suddenly stopped happening yesterday. I'll reopen if I can find more definite replication steps.
