### ISSUE TITLE
Transfer volume across AZ's

### ISSUE THREAD

**Issue by williamparry** [williamparry/cloudRIG#56]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=52927633)](https://www.bountysource.com/issues/52927633-transfer-volume-across-az-s?utm_source=52927633&utm_medium=shield&utm_campaign=ISSUE_BADGE)

In "Add Storage" if a user has a volume in another AZ it shows a warning.

Add a button to "Transfer here", which will:

1) Modify current EBS volume to provisioned iops type
2) Set iops to 50:1 iops:gb (to speed up snapshot creation)
3) Create snapshot
4) Create new volume in current AZ with snapshot
5) Delete original volume

**Comment by artem7902** [comment]
#61 Hi i think i resolve this issue :)

**Comment by artem7902** [comment]
Oh, sorry for so many strings changes. This is stupid formatted in VS Code. If this important i can to try fix it.

**Comment by artem7902** [comment]
#62

**Comment by williamparry** [comment]
I've closed this now - you should be able to claim your bounty. If you have any trouble please let me know.

**Comment by williamparry** [comment]
When you fill up the volume, eventually you get this error:

```Resource is not in the state snapshotCompleted```

**Comment by artem7902** [comment]
Hi, please check it, #71 . Now it must working.
