### ISSUE TITLE
Delete snapshots of cloudRIG AMI

### ISSUE THREAD

**Issue by williamparry** [williamparry/cloudRIG#59]
A snapshot is automatically created when an AMI is made of the cloudRIG instance. These should be suppressed, or deleted.

**Comment by williamparry** [comment]
https://www.bountysource.com/issues/53460915-delete-snapshots-of-cloudrig-ami

**Comment by artem7902** [comment]
#69

**Comment by williamparry** [comment]
Looks to be working :+1:
