### ISSUE TITLE
Add ctrl + v for Parsec Id [$15]

### ISSUE THREAD

**Issue by williamparry** [williamparry/cloudRIG#66]
At the moment you have to right-click to paste in.

**Comment by williamparry** [comment]
https://www.bountysource.com/issues/55468299-add-ctrl-v-for-parsec-id

**Comment by artem7902** [comment]
This strange, ctrl+v works for me, what OS you use?

**Comment by williamparry** [comment]
macOS

**Comment by artem7902** [comment]
Ok, i use Ubuntu and don't have any mac, but i think my mac lovers friends can share with me for couple hours for resolve this issue :) You test it for Windows?)

**Comment by williamparry** [comment]
Oh neat it works for Ubuntu? Does it run well? I've been meaning to test for Windows.

**Comment by artem7902** [comment]
Yea, with Ubuntu it works great. I tested it for mac, owner of PC says me that in Mac instead of ctrl+V usually used command+V, I tried it and it works great. Do you really need ctrl+V on Mac?

**Comment by williamparry** [comment]
You're right, it is command+V on Mac.

Does it work with clicking on the parsec server id field and going CMD + V?

https://pracucci.com/atom-electron-enable-copy-and-paste.html

**Comment by williamparry** [comment]
I have added a bounty for testing releases.

https://github.com/williamparry/cloudRIG/issues/73

**Comment by williamparry** [comment]
Hmm, the command V works for me... Not sure what's going on there.

Have you seen this with your modals being offscreen? Think I might change this ticket to suss that out.

![screen shot 2018-03-09 at 1 08 13 am](https://user-images.githubusercontent.com/348091/37155225-74667418-2336-11e8-8ec8-f91099f8a6ff.png)

**Comment by artem7902** [comment]
Hi, i just put all bugs and test reports here, ok?  #73  Test in process.

**Comment by williamparry** [comment]
Fixed by reverting semantic ui css back.

https://github.com/Semantic-Org/Semantic-UI-React/issues/2549

**Comment by williamparry** [comment]
@artem7902 you can claim this bounty.
