### ISSUE TITLE
Feature: Quick install emulators [$100]

### ISSUE THREAD

**Issue by williamparry** [williamparry/cloudRIG#79]
1. Add install chocolatey to the start functions: https://github.com/williamparry/cloudRIG/blob/dev/lib/index.js#L2607
2. In the UI, where there's the YouTube video playlist, instead have icons that allow the user to click to install an emulator. Use ```sendMessage``` to execute.

**Comment by williamparry** [comment]
https://www.bountysource.com/issues/57460988-feature-quick-install-emulators

**Comment by williamparry** [comment]
Ideally this would be done without chocolatey, but it's OK if it is.

**Comment by artem7902** [comment]
@williamparry Ok, but unfortunately I can't understand what emulator do you want to install. Please explain a little :)

**Comment by williamparry** [comment]
The flow would be, once the the instance is ready, it would swap out the YouTube embed with:
"Install an emulator"

It would have a button with the logo for each one (get as high resolution / svg as you can), and when you click it, it will install chocolatey, and the emulator they chose.

- **N64**
`choco install mupen64plus`
- **SNES**
`choco install snes9x`
- **NES**
`choco install nestopia`
- **Wii U**
`choco install cemu`
- **Wii and GameCube**
`choco install dolphin`
- **SEGA**
`choco install kega-fusion`
- **MAME**
`choco install mame`

**Comment by artem7902** [comment]
@williamparry Ok, thanks for the explanation. I'm starting to work on this.
