### ISSUE TITLE
Custom wallpapers [$30]

### ISSUE THREAD

**Issue by williamparry** [williamparry/cloudRIG#85]
* Background style is the theme of the cloudRIG logo
* Contains cloudRIG and Parsec logos
* Multiple resolutions

Source logo:

[MOCKUP_21Jun18_1606_B54974_2.ai.zip](https://github.com/williamparry/cloudRIG/files/2143302/MOCKUP_21Jun18_1606_B54974_2.ai.zip)

[svg.zip](https://github.com/williamparry/cloudRIG/files/2143345/svg.zip)

**Comment by Prid13** [comment]
Wallpaper 1

![cloudrig wallpaper 1artboard 1](https://user-images.githubusercontent.com/27897747/42467559-86549f24-83b2-11e8-8487-97a18ebfbef8.jpg)

**Comment by Prid13** [comment]
More variants:

![cloudrig wallpaper 2artboard 1](https://user-images.githubusercontent.com/27897747/42468695-ec411af8-83b5-11e8-8669-fab40493e270.jpg)
![cloudrig wallpaper 3artboard 1](https://user-images.githubusercontent.com/27897747/42468696-ec614648-83b5-11e8-9d96-6666245e4bcf.jpg)
![cloudrig wallpaper 4artboard 1](https://user-images.githubusercontent.com/27897747/42468697-ec824ffa-83b5-11e8-85e4-ebec13c37e8a.jpg)

**Comment by williamparry** [comment]
I like the first and last ones. Could I get them in the common resolutions (and high dpi)?

**Comment by Prid13** [comment]
Here you go, common resolutions for the first and the last wallpapers :)

[cloudRIG Wallpapers.zip](https://github.com/williamparry/cloudRIG/files/2181791/cloudRIG.Wallpapers.zip)

**Comment by williamparry** [comment]
Awesome - could I get one size for my patreon? 3200x800

**Comment by Prid13** [comment]
There you go: [cloudRIG Wallpapers Patreon.zip](https://github.com/williamparry/cloudRIG/files/2186938/cloudRIG.Wallpapers.Patreon.zip)

And if you might ever need the Photoshop files: https://files.fm/u/hwyh7pjk

**Comment by williamparry** [comment]
Nice! I'm going to close this so you can claim the bounty.

Could you send me an email at williamparry@gmail.com with an estimate of how much a landing page would cost to design? It just needs to say what's on the README in a nice designed way.
