### ISSUE TITLE
Ability to specify different / smaller storage size 

### ISSUE THREAD

**Issue by tchia04** [williamparry/cloudRIG#99]
When I clicked on the "Add Storage" button, there are only three choices: 100GB, 150GB, and 200GB.

Since you are being charged for the "$0.10 per GB-month of provisioned storage" this mean if you provision 100GB drive but only use 10GB you are still being charged about $10 a month.

https://aws.amazon.com/ebs/pricing/

Can I specify a smaller amount if my steam library is not that big?

**Comment by NitriKx** [comment]
Hi @tchia04, 

This pricing only apply when the instance root volume is provisioned. 
When your instance is shutdown, cloudRIG make a snapshot of the volume before deleting it. 

Snapshots are billed differently: you are only priced for the blocks modified compared to the base AMI. 
For instance if you install a 10GB game, you will only pay for ~10GB of EBS snapshot: 0.05$ * 10 = 0.50$/month.
